# Variables
@baseUrl = https://jsonplaceholder.typicode.com
@postId = 1
@userId = 1
@contentType = application/json

### List all posts
GET {{baseUrl}}/posts

### Get single post
GET {{baseUrl}}/posts/{{postId}}

### Create a new post
POST {{baseUrl}}/posts
Content-Type: {{contentType}}

{
    "title": "Hello from poke!",
    "body": "This is a test request",
    "userId": {{userId}}
}

### Update a post
PUT {{baseUrl}}/posts/{{postId}}
Content-Type: {{contentType}}

{
    "id": {{postId}},
    "title": "Updated title",
    "body": "Updated body",
    "userId": {{userId}}
}

### Delete a post
DELETE {{baseUrl}}/posts/{{postId}}

### Get comments for a post
GET {{baseUrl}}/posts/{{postId}}/comments
